[package]
name = "version-diff"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
regex = "1.11.1"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
